const types = {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    GET_MY_INFO: 'GET_MY_INFO',
    GET_PET_INFO: 'GET_PET_INFO',
    CHANGE_NICKNAME: 'CHANGE_NICKNAME',
    CHANGE_PETNAME: 'CHANGE_PETNAME',
    GET_MAIN_ALARM_LIST: 'GET_MAIN_ALARM_LIST',
    GET_MEDICINE_LIST: 'GET_MEDICINE_LIST',
    SAVE_ALARM_LIST: 'SAVE_ALARM_LIST',
    GET_ALARM_HISTORY: 'GET_ALARM_HISTORY',
    REFRESH_INFO: 'REFRESH_INFO'
};

export default types