const types = {
    CREATE_COMMUNITY_LIST : 'CREATE_COMMUNITY_LIST',
    CHANGE_POST_DETAIL: 'CHANGE_POST_DETAIL',
    RESET_POST_DETAIL: 'RESET_POST_DETAIL',
    RESET_COMMUNITY_LIST : 'RESET_COMMUNITY_LIST',
    GET_COMMUNITY: 'GET_COMMUNITY',
    GET_MORE_COMMUNITY: 'GET_MORE_COMMUNITY',
    GET_COMMUNITY_SEARCH: 'GET_COMMUNITY_SEARCH',
    GET_MORE_COMMUNITY_SEARCH: 'GET_MORE_COMMUNITY_SEARCH',
    RESET_COMMUNITY_SEARCH_VALUE: 'RESET_COMMUNITY_SEARCH_VALUE',
    GET_POST_DETAIL: 'GET_POST_DETAIL'
};

export default types